### ISSUE TITLE
Не обновляется список страниц при создании шаблона

### ISSUE THREAD

**Issue by HDenis** [EdgestileLTD/SiteEdit6.0#10]
`Структура ` > `Шаблоны ` > _"Добавить"_ с опцией _"Создать новую страницу с этим именем"_, новая страница создается, но если перейти обратно в раздел `Страницы` в списке ее не будет, приходится дергать кнопку _"Обновить"_

**Comment by Edgestile** [comment]
Исправлено, при создании шаблона обновляется список страниц
