### ISSUE TITLE
Шаблон отображается будучи не назначенным

### ISSUE THREAD

**Issue by dzino** [EdgestileLTD/SiteEdit6.0#3]
`Страницы` > `Добавить` > _заголовок и псевдоним_ > `Шаблон` отображается будучи не назначенным - должна быть возможность выбора пустого значения (тк _страница_ может быть создана раньше _шаблона_)

**Comment by HDenis** [comment]
Проблема только на клиенте, активный последний пункт в выпадающем списке

**Comment by Edgestile** [comment]
Добавил в список пункт "Выберите шаблон"
